name: File Converter Workflow

on:
  repository_dispatch:
    types: [file-convert-request] # この依頼名で起動

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download video file from transfer service
        run: |
          curl -L -o input_file "${{ github.event.client_payload.download_url }}"
          
      - name: Convert video
        id: convert
        run: |
          original_filename="${{ github.event.client_payload.original_filename }}"
          filename_no_ext="${original_filename%.*}"
          output_filename="converted_${filename_no_ext}.mp4"
          
          # 受け取ったオプションでFFmpegコマンドを組み立てる (例)
          # この部分は後でPHPから渡すオプションに応じて変更可能
          ffmpeg -i input_file -c:v libx264 -crf 28 -c:a aac -b:a 128k "$output_filename"
          
          echo "output_filename=$output_filename" >> $GITHUB_OUTPUT

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-${{ github.event.client_payload.original_filename }}
          path: ${{ steps.convert.outputs.output_filename }}
